import image from "../public/React-Frontend_Language.png"
export const Data = {
    Reactjs : {
        heading : "Introduction to React",
        about :   "React is a framework that employs Webpack to automatically compile React, JSX, and ES6 code while handling CSS file prefixes. React is a JavaScript-based UI development library. Although React is a library rather than a language, it is widely used in web development. The library first appeared in May 2013 and is now one of the most commonly used frontend libraries for web development React offers various extensions for entire application architectural support, such as Flux and React Native, beyond mere UI.  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed, officiis aliquid eveniet facilis soluta reiciendis, laudantium saepe at explicabo inventore amet, harum repellendus magni. Ab, fuga magni dicta dolore necessitatibus voluptatem explicabo. Ullam maiores iste ducimus illo voluptates beatae totam accusantium, voluptatum ex veritatis nostrum quasi quod error cupiditate cumque natus! Dignissimos provident voluptatem laudantium amet. Ipsam, sit doloremque architecto ullam sed ratione minus, quod expedita animi assumenda eaque autem commodi omnis eos. Veritatis reprehenderit mollitia aspernatur consequuntur cum nobis ipsum soluta esse fugiat, libero labore odio atque similique delectus natus placeat expedita maiores? Enim in laudantium nam aliquam assumenda. " ,


    },
    Component : {
        heading : "Introduction to React Component ",
        about :   "Components are rightly defined as the essential building blocks of any application created with React, and a single app most often consists of many components. A component is in essence, a piece of the user interface - splitting the user interface into reusable and independent parts, each of which can be processed separately. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum reprehenderit amet perspiciatis facere in a consequuntur doloremque vero vel, officia quasi ea? Quos est odit eius. Labore alias, ad ullam obcaecati unde dolore aspernatur magnam architecto nesciunt nulla, facere reiciendis optio officia fugiat nam dolorum error repellendus iusto quasi. Ipsum nemo ratione tempora dolor, est magni voluptate explicabo sint. Officia est dignissimos quos ad voluptatem eligendi repellat hic! Est numquam dolore nam nostrum tempore eum quae aspernatur reprehenderit excepturi deleniti necessitatibus, exercitationem aut ipsam doloremque, quasi debitis accusamus fugiat, inventore quisquam. Esse quis voluptates, eius nisi quisquam labore mollitia corrupti! " ,
    },
    Props : {
        heading : "Introduction to React Props",
        about :   "ReactJS being a component-based library, the user interface (UI) is divided into small, reusable pieces. These components might need to send data to each other in some scenarios, and passing data between the components is done by way of props. The term props stands for properties and is used for passing data from one component to another. As opposed to state in React, props are read-only. So, the data coming from a parent component can't be changed by the child component. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempore voluptatum excepturi sapiente. Libero modi dolorem doloribus, ea repellat sapiente enim similique suscipit numquam voluptas aliquam quae dolores, pariatur, autem reiciendis quaerat corporis repellendus. Natus iste aperiam accusantium eveniet, consectetur veniam, nemo omnis, doloribus alias perspiciatis aliquid iusto odio possimus maiores tempora earum temporibus quia magni totam cupiditate deserunt! Dolore magni illo aut ex enim illum doloremque, consequuntur provident quibusdam vero minima, iste ab dolorum labore libero quaerat amet ullam nihil debitis? Error illo quidem saepe delectus neque sint ipsa est reprehenderit ad at quia, provident sit, eius, similique veniam consectetur. " ,
    

    },
    UseState : {
        heading : "Introduction to React UseState",
        about :   "useState is a Hook, so you can only call it at the top level of your component or your own Hooks. You can’t call it inside loops or conditions. If you need that, extract a new component and move the state into it.In Strict Mode, React will call your initializer function twice in order to help you find accidental impurities. This is development-only behavior and does not affect production. If your initializer function is pure (as it should be), this should not affect the behavior. The result from one of the calls will be ignored Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum reprehenderit non nostrum eligendi nesciunt eum eaque unde dolor, neque suscipit? Expedita aliquam repellat ut nisi numquam illum unde odit porro quia odio quibusdam et delectus aperiam provident similique quisquam praesentium veritatis quos sequi, laborum dolorum. Iure nesciunt veritatis culpa dolorem? " ,

    },
}